#' Summarize chain output from NIMBLE
#'
#' @param samples (list) output from NIMBLE
#' @param data (list) data created and formatted for NIMBLE by data_for_NIMBLE()$data
#' @param constants (list) constants created and formatted for NIMBLE by data_for_NIMBLE()$constants
#' @param project (numeric) the number of projections to calculate
#' @param coarse.grid (logical) whether a coarse grid was used for the spatial model
#' @param cutoff (numeric) where to cutoff chains in addition to the burnin; Default is 0
#' @param block.out (character or numeric) which block is excluded
#' @param gridkey (data.frame) contains conus.grid.id and associated grid.ids to use for indexing in NIMBLE
#' @param spatkey (data.frame) spatial key generated by make_spatkey() and stored in spatRegion
#' @param effort (logical) whether to trace effort parameters (T) or not (F)
#' @param SLURM (logical) whether a SLURM-based high-performance computing cluster is being used
#'
#' @returns
#' @export
#'
#' @importFrom rlang .data
#' @importFrom dplyr right_join bind_rows mutate slice mutate inner_join select group_by ungroup left_join row_number
#' @importFrom coda as.mcmc
#' @importFrom parallel makeCluster parLapply stopCluster
#' @import nimble


summarize_samples <- function(samples,
                              data,
                              constants,
                              project = 0,
                              coarse.grid,
                              cutoff = 0,
                              block.out,
                              gridkey,
                              spatkey = NULL,
                              effort = F,
                              SLURM = F) {


  # Summarize chains in parallel ----

  # select which chains to use
  chains <- 1:length(samples)

  cat("Summarizing chains...\n")

  if (SLURM) {
    cores <- get_cpus_per_task() - 1
  } else {
    cores <- 5
  }

  start <- Sys.time()
  this_cluster <- makeCluster(cores)
  out <- parLapply(cl = this_cluster,
                   X = 1:ncol(samples[[1]]),
                   fun = chain_summary,
                   samples = samples,
                   chains = chains,
                   cutoff = cutoff)
  stopCluster(this_cluster)


  out <- bind_rows(out)
  print(Sys.time() - start)

  cat('Chain summarization complete \n')

  dat <- list(out = out)

  # Reformat estimated parameters ----
  # lambda
  keep <- grep("lambda0", out$param)
  lambda0 <- out %>%
              slice(keep) %>%
              mutate(grid.id = as.numeric(gsub("lambda0", "", .data$param)),
                     block.out = block.out) %>%
              inner_join(gridkey, by = "grid.id")  %>%
              select(.data$conus.grid.id, .data$group, .data$block.out,
                     .data$mean, .data$lo, .data$hi, .data$lotail, .data$hitail,
                     .data$unc.range, .data$unc.rel, .data$rhat, .data$ESS)

  dat$lambda0 <- lambda0

  # psi
  keep <- grep("psi0", out$param)
  psi0 <- out %>%
            slice(keep) %>%
            mutate(grid.id = as.numeric(gsub("psi0", "", .data$param)),
                   block.out = block.out) %>%
            inner_join(gridkey, by = "grid.id") %>%
            select(.data$conus.grid.id, .data$group, .data$block.out, .data$mean,
                   .data$lo, .data$hi, .data$lotail, .data$hitail, .data$unc.range,
                   .data$unc.rel, .data$rhat, .data$ESS)

  dat$psi0 <- psi0

  # XB
  keep <- grep("XB0", out$param)
  XB0 <- out %>%
          slice(keep) %>%
          mutate(grid.id = as.numeric(gsub("XB0", "", .data$param)),
                 block.out = block.out) %>%
          inner_join(gridkey, by = "grid.id") %>%
          select(.data$conus.grid.id, .data$group, .data$block.out, .data$mean,
                 .data$lo, .data$hi, .data$lotail, .data$hitail, .data$unc.range,
                 .data$unc.rel, .data$rhat, .data$ESS)

  dat$XB0 <- XB0

  # effort
  if (effort == T) {
    datasetnames <- grep("nW", names(constants))
    datasetnames <- gsub("nW", "", names(constants)[datasetnames])
    datasetnames <- grep(paste0("name", datasetnames, collapse = "|"), names(constants))
    dnames <- c()
    for (i in 1:length(datasetnames)) {
      dnames <- c(dnames, constants[[datasetnames[i]]])
    }
    dnames <- data.frame(PO.dataset = paste0("E", 1:length(dnames)),
                         PO.dataset.name = dnames)

    keep <- grep("E", out$param)
    Enames <- colnames(samples[[1]][grep("E", colnames(samples[[1]]))])
    E <- out %>%
      slice(keep) %>%
      mutate(name1 = Enames,
             grid.id = gsub(".*[[]", "", .data$name1),
             grid.id = as.numeric(gsub("[]]", "", .data$grid.id)),
             PO.dataset = gsub("[[].*", "", .data$name1),
             block.out = block.out) %>%
      inner_join(gridkey, by = "grid.id") %>%
      inner_join(dnames, by = "PO.dataset") %>%
      select(.data$conus.grid.id, .data$PO.dataset.name, .data$group,
             .data$block.out, .data$mean, .data$lo, .data$hi, .data$lotail,
             .data$hitail, .data$unc.range, .data$unc.rel, .data$rhat, .data$ESS)

    dat$effort <- E
  }

  if (project > 0) {
    for (z in 1:project) {
      # lambda
      keep <- grep(paste0("lambda", z), out$param)
      lambda0 <- out %>%
                  slice(keep) %>%
                  mutate(grid.id = as.numeric(gsub(paste0("lambda", z), "", .data$param)),
                         block.out = block.out) %>%
                  inner_join(gridkey, by = "grid.id") %>%
                  select(.data$conus.grid.id, .data$group, .data$block.out,
                         .data$mean, .data$lo, .data$hi, .data$lotail,
                         .data$hitail, .data$unc.range, .data$unc.rel, .data$rhat,
                         .data$ESS)

      dat[[paste0("lambda", z)]] <- lambda0

      # psi
      keep <- grep(paste0("psi", z), out$param)
      psi0 <- out %>%
                slice(keep) %>%
                mutate(grid.id = as.numeric(gsub(paste0("psi", z), "", .data$param)),
                       block.out = block.out) %>%
                inner_join(gridkey, by = "grid.id") %>%
                select(.data$conus.grid.id, .data$group, .data$block.out,
                       .data$mean, .data$lo, .data$hi, .data$lotail,
                       .data$hitail, .data$unc.range, .data$unc.rel, .data$rhat,
                       .data$ESS)

      dat[[paste0("psi", z)]] <- psi0

      # XB
      keep <- grep(paste0("XB", z), out$param)
      XB0 <- out %>%
              slice(keep) %>%
              mutate(grid.id = as.numeric(gsub(paste0("XB", z), "", .data$param)),
                     block.out = block.out) %>%
              inner_join(gridkey, by = "grid.id") %>%
              select(.data$conus.grid.id, .data$group, .data$block.out,
                     .data$mean, .data$lo, .data$hi, .data$lotail, .data$hitail,
                     .data$unc.range, .data$unc.rel, .data$rhat, .data$ESS)

      dat[[paste0("XB", z)]] <- XB0
    }
  }

  if (coarse.grid == T) {
    key <- left_join(gridkey, spatkey, by = 'conus.grid.id')
  } else {
    key <- mutate(gridkey, spat.grid.id = .data$grid.id)
  }

  # spat
  keep <- grep("spat", out$param)
  if (length(keep) > 0) {
    spat <- out %>%
              slice(keep) %>%
              mutate(grid.id = as.numeric(gsub("spat", "", .data$param)),
                     block.out = block.out) %>%
      # Changed following line from:
      # left_join(key, ., by = c("spat.grid.id" = "grid.id"))
              right_join(key, by = c("spat.grid.id" = "grid.id")) %>%
              select(.data$conus.grid.id, .data$group, .data$block.out,
                     .data$mean, .data$lo, .data$hi, .data$lotail, .data$hitail,
                     .data$unc.range, .data$unc.rel, .data$rhat, .data$ESS)

    dat$spat <- spat
  }

  # B
  keep <- grep("B", out$param)
  dontkeep <- grep("XB", out$param)
  keep <- keep[-which(keep %in% dontkeep)]
  process.coef <- out %>%
                  slice(keep) %>%
                  mutate(covariate = colnames(data$Xz), block.out = block.out) %>%
                  select(.data$covariate, .data$block.out, .data$mean, .data$lo,
                         .data$hi, .data$lotail, .data$hitail, .data$unc.range,
                         .data$unc.rel, .data$rhat, .data$ESS)

  dat$process.coef <- process.coef

  # Dataset intercept
  datasets <- data.frame(name = unlist(constants[grep("name", names(constants))]),
                         number = names(constants)[grep("name", names(constants))],
                         ncov = names(constants)[grep("nCovW|nCovV|nCovY", names(constants))]) %>%
    mutate(type = substr(.data$ncov, 5, 5),
           data.type = case_when(type == "V" ~ "DND", type == "Y" ~ "Count",
                                 type == "W" ~ "PO"),
           number = gsub("name", "", .data$number)) %>%
    select(.data$name, .data$number, .data$data.type)

  # alpha
  keep <- grep("alpha", out$param)
  alpha <- out %>%
            slice(keep) %>%
            mutate(number = gsub("alpha", "", .data$param), block.out = block.out) %>%
            left_join(datasets, by = "number") %>%
            select(.data$name, .data$data.type, .data$block.out, .data$mean,
                   .data$lo, .data$hi, .data$lotail, .data$hitail,
                   .data$unc.range, .data$unc.rel, .data$rhat, .data$ESS)

  dat$alpha <- alpha

  # Dataset covariates
  Xs <- grep("X", names(data))
  rm <- grep("Xz", names(data)) # get rid of Xzs
  Xs <- Xs[-which(Xs %in% rm)]
  obs.covs <- c()
  for (x in 1:length(Xs)) {
    if (ncol(data[[Xs[x]]]) == 0)
      next

    df <- data.frame(
      number = substr(names(data)[Xs[x]], 3, nchar(names(data)[Xs[x]])),
      covariate = colnames(data[[Xs[x]]]),
      colnumber = 1:ncol(data[[Xs[x]]])
    )
    obs.covs <- bind_rows(obs.covs, df)
  }

  keep <- grep("A|C|D", out$param)
  obs.coef <- out %>%
                slice(keep) %>%
                mutate(number = substr(.data$param, 2, nchar(.data$param) - 1)) %>%
                group_by(.data$number) %>%
                mutate(colnumber = row_number(), block.out = block.out) %>%
                ungroup() %>%
                left_join(datasets, by = "number") %>%
                left_join(obs.covs, by = c("number", "colnumber")) %>%
                select(.data$name, .data$data.type, .data$covariate,
                       .data$block.out, .data$mean, .data$lo, .data$hi,
                       .data$lotail, .data$hitail, .data$unc.range, .data$unc.rel,
                       .data$rhat, .data$ESS)

  dat$obs.coef <- obs.coef


  # Tau
  keep <- grep("tau", out$param)
  tau <- out %>%
    slice(keep) %>%
    mutate(block.out = block.out) %>%
    select(.data$block.out, .data$mean, .data$lo, .data$hi, .data$lotail,
           .data$hitail, .data$unc.range, .data$unc.rel, .data$rhat, .data$ESS)
  dat$tau <- tau

  # Return
  return(dat)

}
