#' Summarize chain output from NIMBLE
#'
#' @param samples (list) output from NIMBLE
#' @param data (list) data created and formatted for NIMBLE by data_for_NIMBLE()$data
#' @param constants (list) constants created and formatted for NIMBLE by data_for_NIMBLE()$constants
#' @param project (numeric) the number of projections to calculate
#' @param coarse.grid (logical) whether a coarse grid was used for the spatial model
#' @param cutoff (numeric) where to cutoff chains in addition to the burnin; Default is 0
#' @param block.out (character or numeric) which block is excluded
#' @param gridkey (data.frame) contains conus.grid.id and associated grid.ids to use for indexing in NIMBLE
#' @param spatkey (data.frame) spatial key generated by make_spatkey() and stored in spatRegion
#' @param SLURM (logical) whether a SLURM-based high-performance computing cluster is being used
#'
#' @returns
#' @export
#'
#' @importFrom dplyr bind_rows mutate slice mutate inner_join select group_by ungroup left_join row_number
#' @importFrom coda as.mcmc
#' @importFrom parallel makeCluster parLapply stopCluster
#' @import nimble
#'
#' @examples


summarize_samples <- function(samples,
                              data,
                              constants,
                              project = 0,
                              coarse.grid,
                              cutoff = 0,
                              block.out,
                              gridkey,
                              spatkey = NULL,
                              SLURM = F) {


  # Summarize chains in parallel ----

  # select which chains to use
  chains <- 1:length(samples)

  cat("Summarizing chains...\n")

  if (SLURM) {
    cores <- get_cpus_per_task() - 1
  } else {
    cores <- 5
  }

  start <- Sys.time()
  this_cluster <- parallel::makeCluster(cores)
  out <- parallel::parLapply(cl = this_cluster,
                             X = 1:ncol(samples[[1]]),
                             fun = chain_summary,
                             samples = samples,
                             chains = chains,
                             cutoff = cutoff)
  parallel::stopCluster(this_cluster)


  out <- dplyr::bind_rows(out)
  print(Sys.time() - start)

  cat('Chain summarization complete \n')

  dat <- list(out = out)

  # Reformat estimated parameters ----
  # lambda
  keep <- grep("lambda0", out$param)
  lambda0 <- out %>%
              dplyr::slice(keep) %>%
              dplyr::mutate(grid.id = as.numeric(gsub("lambda0", "", param)), block.out = block.out) %>%
              dplyr::inner_join(gridkey, by = "grid.id")  %>%
              dplyr::select(conus.grid.id, group, block.out, mean, lo, hi,
                            lotail, hitail,unc.range, unc.rel, rhat, ESS)

  dat$lambda0 <- lambda0

  # psi
  keep <- grep("psi0", out$param)
  psi0 <- out %>%
            dplyr::slice(keep) %>%
            dplyr::mutate(grid.id = as.numeric(gsub("psi0", "", param)), block.out = block.out) %>%
            dplyr::inner_join(gridkey, by = "grid.id") %>%
            dplyr::select(conus.grid.id, group, block.out, mean, lo, hi,
                          lotail, hitail, unc.range, unc.rel, rhat, ESS)

  dat$psi0 <- psi0

  # XB
  keep <- grep("XB0", out$param)
  XB0 <- out %>%
          dplyr::slice(keep) %>%
          dplyr::mutate(grid.id = as.numeric(gsub("XB0", "", param)), block.out = block.out) %>%
          dplyr::inner_join(gridkey, by = "grid.id") %>%
          dplyr::select(conus.grid.id, group, block.out, mean, lo, hi,
                        lotail, hitail, unc.range, unc.rel, rhat, ESS)

  dat$XB0 <- XB0

  if (project > 0) {
    for (z in 1:project) {
      # lambda
      keep <- grep(paste0("lambda", z), out$param)
      lambda0 <- out %>%
                  dplyr::slice(keep) %>%
                  dplyr::mutate(grid.id = as.numeric(gsub(paste0("lambda", z), "", param)), block.out = block.out) %>%
                  dplyr::inner_join(gridkey, by = "grid.id") %>%
                  dplyr::select(conus.grid.id, group, block.out, mean, lo, hi,
                                lotail, hitail, unc.range, unc.rel, rhat, ESS)

      dat[[paste0("lambda", z)]] <- lambda0

      # psi
      keep <- grep(paste0("psi", z), out$param)
      psi0 <- out %>%
                dplyr::slice(keep) %>%
                dplyr::mutate(grid.id = as.numeric(gsub(paste0("psi", z), "", param)), block.out = block.out) %>%
                dplyr::inner_join(gridkey, by = "grid.id") %>%
                dplyr::select(conus.grid.id, group, block.out, mean, lo, hi,
                              lotail, hitail, unc.range, unc.rel, rhat, ESS)

      dat[[paste0("psi", z)]] <- psi0

      # XB
      keep <- grep(paste0("XB", z), out$param)
      XB0 <- out %>%
              dplyr::slice(keep) %>%
              dplyr::mutate(grid.id = as.numeric(gsub(paste0("XB", z), "", param)), block.out = block.out) %>%
              dplyr::inner_join(gridkey, by = "grid.id") %>%
              dplyr::select(conus.grid.id, group, block.out, mean, lo, hi,
                            lotail, hitail, unc.range, unc.rel, rhat, ESS)

      dat[[paste0("XB", z)]] <- XB0
    }
  }

  if (coarse.grid == T) {
    key <- dplyr::left_join(gridkey, spatkey, by = 'conus.grid.id')
  } else {
    key <- dplyr::mutate(gridkey, spat.grid.id = grid.id)
  }

  # spat
  keep <- grep("spat", out$param)
  if (length(keep) > 0) {
    spat <- out %>%
              dplyr::slice(keep) %>%
              dplyr::mutate(grid.id = as.numeric(gsub("spat", "", param)), block.out = block.out) %>%
              dplyr::left_join(key, ., by = c("spat.grid.id" = "grid.id")) %>%
              dplyr::select(conus.grid.id, group, block.out, mean, lo, hi,
                            lotail, hitail, unc.range, unc.rel, rhat, ESS)

    dat$spat <- spat
  }

  # B
  keep <- grep("B", out$param)
  dontkeep <- grep("XB", out$param)
  keep <- keep[-which(keep %in% dontkeep)]
  process.coef <- out %>%
                  dplyr::slice(keep) %>%
                  dplyr::mutate(covariate = colnames(data$Xz), block.out = block.out) %>%
                  dplyr::select(covariate, block.out, mean, lo, hi, lotail, hitail,
                                unc.range, unc.rel, rhat, ESS)

  dat$process.coef <- process.coef

  # Dataset intercept
  datasets <- data.frame(
    name = unlist(constants[grep("name", names(constants))]),
    number = names(constants)[grep("name", names(constants))],
    ncov = names(constants)[grep("nCovW|nCovV|nCovY", names(constants))]
  ) %>%
    dplyr::mutate(
      type = substr(ncov, 5, 5),
      data.type = dplyr::case_when(type == "V" ~ "DND", type == "Y" ~ "Count", type == "W" ~ "PO"),
      number = gsub("name", "", number)
    ) %>%
    dplyr::select(name, number, data.type)

  # alpha
  keep <- grep("alpha", out$param)
  alpha <- out %>%
            dplyr::slice(keep) %>%
            dplyr::mutate(number = gsub("alpha", "", param), block.out = block.out) %>%
            dplyr::left_join(datasets, by = "number") %>%
            dplyr::select(name, data.type, block.out, mean, lo, hi, lotail, hitail,
                          unc.range, unc.rel, rhat, ESS)

  dat$alpha <- alpha

  # Dataset covariates
  Xs <- grep("X", names(data))
  rm <- grep("Xz", names(data)) # get rid of Xzs
  Xs <- Xs[-which(Xs %in% rm)]
  obs.covs <- c()
  for (x in 1:length(Xs)) {
    if (ncol(data[[Xs[x]]]) == 0)
      next

    df <- data.frame(
      number = substr(names(data)[Xs[x]], 3, nchar(names(data)[Xs[x]])),
      covariate = colnames(data[[Xs[x]]]),
      colnumber = 1:ncol(data[[Xs[x]]])
    )
    obs.covs <- dplyr::bind_rows(obs.covs, df)
  }

  keep <- grep("A|C|D", out$param)
  obs.coef <- out %>%
                dplyr::slice(keep) %>%
                dplyr::mutate(number = substr(param, 2, nchar(param) - 1)) %>%
                dplyr::group_by(number) %>%
                dplyr::mutate(colnumber = dplyr::row_number(), block.out = block.out) %>%
                dplyr::ungroup() %>%
                dplyr::left_join(datasets, by = "number") %>%
                dplyr::left_join(obs.covs, by = c("number", "colnumber")) %>%
                dplyr::select(name, data.type, covariate, block.out, mean, lo, hi,
                              lotail, hitail, unc.range, unc.rel, rhat, ESS)

  dat$obs.coef <- obs.coef

  # Return
  return(dat)
}
