#' Summarize chain output from NIMBLE
#'
#' @param samples (list) output from NIMBLE
#' @param data (list) data created and formatted for NIMBLE by data_for_NIMBLE()$data
#' @param constants (list) constants created and formatted for NIMBLE by data_for_NIMBLE()$constants
#' @param project (numeric) the number of projections to calculate
#' @param coarse.grid (logical) whether a coarse grid was used for the spatial model
#' @param cutoff (numeric) where to cutoff chains in addition to the burnin; Default is 0
#' @param block.out (character or numeric) which block is excluded
#' @param gridkey (data.frame) contains conus.grid.id and associated grid.ids to use for indexing in NIMBLE
#' @param spatkey (data.frame) spatial key generated by make_spatkey() and stored in spatRegion
#' @param effort (logical) whether to trace effort parameters (T) or not (F)
#' @param SLURM (logical) whether a SLURM-based high-performance computing cluster is being used
#'
#' @returns A list; Each element is a summarized traced or projected parameter
#' @export
#'
#' @importFrom rlang .data
#' @importFrom dplyr right_join bind_rows mutate slice mutate inner_join select group_by ungroup left_join row_number
#' @importFrom coda as.mcmc
#' @importFrom parallel makeCluster parLapply stopCluster
#' @import nimble


summarize_samples <- function(samples,
                              data,
                              constants,
                              project = 0,
                              coarse.grid,
                              cutoff = 0,
                              block.out,
                              gridkey,
                              spatkey = NULL,
                              effort = F,
                              SLURM = F) {


  # Summarize chains in parallel ----

  # select which chains to use
  chains <- 1:length(samples)

  cat("Summarizing chains...\n")

  if (SLURM) {
    cores <- get_cpus_per_task() - 1
  } else {
    # Source - https://stackoverflow.com/a/50571533
    # Posted by Alexis, modified by community. See post 'Timeline' for change history
    # Retrieved 2026-02-10, License - CC BY-SA 4.0

    chk <- Sys.getenv("_R_CHECK_LIMIT_CORES_", "")

    if (nzchar(chk) && chk == "TRUE") {
      # use 2 cores in CRAN
      cores <- 2L
    } else {
      # use all cores in devtools::test()
      cores <- max(1, parallel::detectCores() - 1)
    }
  }



  start <- Sys.time()
  this_cluster <- makeCluster(cores)

  out <- parLapply(cl = this_cluster,
                   X = 1:ncol(samples[[1]]),
                   fun = chain_summary,
                   samples = samples,
                   chains = chains,
                   cutoff = cutoff)

  on.exit(stopCluster(this_cluster), add = TRUE)



  out <- bind_rows(out)
  print(Sys.time() - start)

  cat('Chain summarization complete \n')

  dat <- list(out = out)

  # Reformat estimated parameters ----
  # lambda
  keep <- grep("lambda0", out$param)
  lambda0 <- out %>%
              slice(keep) %>%
              mutate(grid.id = as.numeric(gsub("lambda0", "", .data$param)),
                     block.out = as.character(block.out)) %>%
              inner_join(gridkey, by = "grid.id")  %>%
              select("conus.grid.id", "group", "block.out", "mean", "lo", "hi",
                     "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

  dat$lambda0 <- lambda0

  # psi
  keep <- grep("psi0", out$param)
  psi0 <- out %>%
            slice(keep) %>%
            mutate(grid.id = as.numeric(gsub("psi0", "", .data$param)),
                   block.out = as.character(block.out)) %>%
            inner_join(gridkey, by = "grid.id") %>%
            select("conus.grid.id", "group", "block.out", "mean", "lo", "hi",
                   "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

  dat$psi0 <- psi0

  # XB
  keep <- grep("XB0", out$param)
  XB0 <- out %>%
          slice(keep) %>%
          mutate(grid.id = as.numeric(gsub("XB0", "", .data$param)),
                 block.out = as.character(block.out)) %>%
          inner_join(gridkey, by = "grid.id") %>%
          select("conus.grid.id", "group", "block.out", "mean", "lo", "hi",
                 "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

  dat$XB0 <- XB0

  # effort
  if (effort == T) {
    datasetnames <- grep("nW", names(constants))
    datasetnames <- gsub("nW", "", names(constants)[datasetnames])
    datasetnames <- grep(paste0("name", datasetnames, collapse = "|"), names(constants))

    dnames <- c()
    cellsall <- c()
    for (i in 1:length(datasetnames)) {
      dnames <- c(dnames, constants[[datasetnames[i]]])

      cells <- data.frame(PO.dataset = paste0("E", i),
                          grid.id = constants[[paste0("Wcells", i)]],
                          ind = 1:length(constants[[paste0("Wcells", i)]]))
      cellsall <- bind_rows(cellsall, cells)
    }
    dnames <- data.frame(PO.dataset = paste0("E", 1:length(dnames)),
                         PO.dataset.name = dnames)

    Enames <- colnames(samples[[1]][grep("E", colnames(samples[[1]]))])

    keep <- grep("E", out$param)
    E <- out %>%
      slice(keep) %>%
      mutate(name1 = Enames) %>%
      mutate(ind = gsub(".*[[]", "", .data$name1),
             ind = as.numeric(gsub("[]]", "", .data$ind)),
             PO.dataset = gsub("[[].*", "", .data$name1),
             block.out = as.character(block.out)) %>%
      full_join(cellsall, by = c("PO.dataset", "ind")) %>%
      inner_join(gridkey, by = "grid.id") %>%
      inner_join(dnames, by = "PO.dataset") %>%
      select("conus.grid.id", "PO.dataset.name", "group", "block.out", "mean",
             'lo', "hi", "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

    dat$effort <- E
  }

  if (project > 0) {
    for (z in 1:project) {
      # lambda
      keep <- grep(paste0("lambda", z), out$param)
      lambda0 <- out %>%
                  slice(keep) %>%
                  mutate(grid.id = as.numeric(gsub(paste0("lambda", z), "", .data$param)),
                         block.out = as.character(block.out)) %>%
                  inner_join(gridkey, by = "grid.id") %>%
                  select("conus.grid.id", "group", "block.out", "mean", "lo",
                         "hi", "lotail", "hitail", "unc.range", "unc.rel", "rhat",
                         "ESS")

      dat[[paste0("lambda", z)]] <- lambda0

      # psi
      keep <- grep(paste0("psi", z), out$param)
      psi0 <- out %>%
                slice(keep) %>%
                mutate(grid.id = as.numeric(gsub(paste0("psi", z), "", .data$param)),
                       block.out = as.character(block.out)) %>%
                inner_join(gridkey, by = "grid.id") %>%
                select("conus.grid.id", "group", "block.out", "mean", "lo", "hi",
                       "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

      dat[[paste0("psi", z)]] <- psi0

      # XB
      keep <- grep(paste0("XB", z), out$param)
      XB0 <- out %>%
              slice(keep) %>%
              mutate(grid.id = as.numeric(gsub(paste0("XB", z), "", .data$param)),
                     block.out = as.character(block.out)) %>%
              inner_join(gridkey, by = "grid.id") %>%
              select("conus.grid.id", "group", "block.out", "mean", "lo", "hi",
                     "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

      dat[[paste0("XB", z)]] <- XB0
    }
  }

  if (coarse.grid == T) {
    key <- left_join(gridkey, spatkey, by = 'conus.grid.id') %>%
            select(-"grid.id") %>% rename("grid.id" = "spat.grid.id")
  } else {
    key <- gridkey
    # mutate(gridkey, spat.grid.id = .data$grid.id) %>%
    #         select(-"grid.id")
  }

  # spat
  keep <- grep("spat", out$param)
  if (length(keep) > 0) {
    spat <- out %>%
              slice(keep) %>%
              mutate(grid.id = as.numeric(gsub("spat", "", .data$param)),
                     block.out = as.character(block.out)) %>%
      # Changed following line from:
              left_join(key, .data, by = "grid.id") %>%
              select("conus.grid.id", "group", "block.out", "mean", "lo", "hi",
                     "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

    dat$spat <- spat
  }

  # B
  keep <- grep("B", out$param)
  dontkeep <- grep("XB", out$param)
  keep <- keep[-which(keep %in% dontkeep)]
  process.coef <- out %>%
                  slice(keep) %>%
                  mutate(covariate = colnames(data$Xz), block.out = as.character(block.out)) %>%
                  select("covariate", "block.out", "mean", "lo", "hi", "lotail",
                         "hitail", "unc.range", "unc.rel", "rhat", "ESS")

  dat$process.coef <- process.coef

  # Dataset intercept
  datasets <- data.frame(name = unlist(constants[grep("name", names(constants))]),
                         number = names(constants)[grep("name", names(constants))],
                         ncov = names(constants)[grep("nCovW|nCovV|nCovY", names(constants))]) %>%
    mutate(type = substr(.data$ncov, 5, 5),
           data.type = case_when(type == "V" ~ "DND", type == "Y" ~ "Count",
                                 type == "W" ~ "PO"),
           number = gsub("name", "", .data$number)) %>%
    select("name", "number", "data.type")

  # alpha
  keep <- grep("alpha", out$param)
  alpha <- out %>%
            slice(keep) %>%
            mutate(number = gsub("alpha", "", .data$param), block.out = as.character(block.out)) %>%
            left_join(datasets, by = "number") %>%
            select("name", "data.type", "block.out", "mean", "lo", "hi",
                   "lotail", "hitail", "unc.range", "unc.rel", "rhat", "ESS")

  dat$alpha <- alpha

  # Dataset covariates
  Xs <- grep("X", names(data))
  rm <- grep("Xz", names(data)) # get rid of Xzs
  Xs <- Xs[-which(Xs %in% rm)]
  obs.covs <- c()
  for (x in 1:length(Xs)) {
    if (ncol(data[[Xs[x]]]) == 0)
      next

    df <- data.frame(
      number = substr(names(data)[Xs[x]], 3, nchar(names(data)[Xs[x]])),
      covariate = colnames(data[[Xs[x]]]),
      colnumber = 1:ncol(data[[Xs[x]]])
    )
    obs.covs <- bind_rows(obs.covs, df)
  }

  keep <- grep("A|C|D", out$param)
  obs.coef <- out %>%
                slice(keep) %>%
                mutate(number = substr(.data$param, 2, nchar(.data$param) - 1)) %>%
                group_by(.data$number) %>%
                mutate(colnumber = row_number(), block.out = as.character(block.out)) %>%
                ungroup() %>%
                left_join(datasets, by = "number") %>%
                left_join(obs.covs, by = c("number", "colnumber")) %>%
                select("name", "data.type", "covariate", "block.out", "mean",
                       "lo", "hi", "lotail", "hitail", "unc.range", "unc.rel",
                       "rhat", "ESS")

  dat$obs.coef <- obs.coef


  # Tau
  keep <- grep("tau", out$param)
  tau <- out %>%
          slice(keep) %>%
          mutate(block.out = as.character(block.out)) %>%
          select("block.out", "mean", "lo", "hi", "lotail", "hitail", "unc.range",
                 "unc.rel", "rhat", "ESS")
  dat$tau <- tau

  # Return
  return(dat)

}
